eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8763

spring:
  application:
    name: pedido
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pedido;MODE=PostgreSQL;
    username: user
    password: undefined
  jpa:
    hibernate:
      ddl-auto: update